### ISSUE TITLE
Clarification in README excludeScope option

### ISSUE THREAD

**Issue by spicalous** [DockYard/ember-service-worker-index#21]
Hi team!

README states
```
// Bypass esw-index and don't serve cached index file for matching URLs
excludeScope: [/\/non-ember-app(\/.*)?$/, /\/another-app(\/.*)?$/],
```

After debugging the service worker code, it looks like the url passed to the [test function [0]](https://github.com/DockYard/ember-service-worker-index/blob/master/service-worker/index.js#L41) is passed the full url
e.g. `http://localhost:4200/non-ember-app/some-path`

in which case the urls in the examples would not be excluded

1. Do I have a misunderstanding in how to configure the `excludeScope`?
2. Should the `excludeScope` also account for the host? e.g. `/.*\/non-ember-app(\/.*)?$/`

I can submit a PR to add clarification in the README

[0] https://github.com/DockYard/ember-service-worker-index/blob/master/service-worker/index.js#L41

Thanks!

**Comment by BrennanRoberts** [comment]
Hey @spicalous, `excludeScope` wasn't working for me, either, so I thought it might be this issue. But then it turned out we were using the wrong top-level `ember-cli-build` config key: `ember-service-worker-index:` rather than `esw-index`.

The path in the example does get matched by the first `excludeScope` example config, even though it gets passed the full URL, as [it uses RegExp.prototype.test()](https://github.com/DockYard/ember-service-worker/blob/4564e495666865b80fd29daf15784e2801b59d1b/service-worker/url-utils.js#L33).

```
> /\/non-ember-app(\/.*)?$/.test("http://localhost:4200/non-ember-app/some-path")
true
```

**Comment by spicalous** [comment]
Going to close as I am no longer using this functionality :) Thanks for adding to the discussion!
