### ISSUE TITLE
Returns blank page when Fastboot is enabled

### ISSUE THREAD

**Issue by balinterdi** [DockYard/ember-service-worker-index#5]
## Version
0.6.3

## Test Case
It's in a branch of the [R&R app](https://github.com/balinterdi/rarwe-code), which is a private repo, but I can give anyone access who wants to take a look.

## Steps to reproduce
Load the app so that SW fills up its caches in Cache Storage. Now turn off JavaScript and reload the app.

## Expected Behavior
A non-blank page (the list of bands and a "Select a band" text) should be rendered as SSR via Fastboot is enabled.

## Actual Behavior
A blank page is rendered (which also fails the Lighthouse audit.)

## More details

It's really the combination of ember-service-worker-index and Fastboot which makes the page be rendered empty (and the “Contains some content when JavaScript is not available” audit to fail). I also tracked down the point where the empty content is cached into the SW cache.

Fastboot has a placeholder text () where it renders the actual content rendered on the server-side. The empty cached content still contains that placeholder (instead of the actual rendered content, which works fine when querying via curl and accept header text/html) so it seems that the SW is "too eager", it caches the content before Fastboot has a chance to do its work and replace the placeholder.

**Comment by ghost** [comment]
This is expected behaviour. By default it caches copy of `/index.html`, which FastBoot will serve as an asset. If you don't want that, you can configure it to cache `/` instead, but I would not recommend doing that.

**Comment by balinterdi** [comment]
Thank you.

I'm somewhat of a newbie when it comes to PWAs but

1) Isn't what I described something that lots of applications bump into? If so, is their solution just caching `/` as you describe?
2) Why is caching `/` not recommended?
3) Can ember-service-worker-index be made to cache the index.html *after* Fastboot replaced the placeholder with the server-rendered content?

Perhaps relatedly, I made a change to the `esw-cache-fallback` configuration and now it seems to work just fine:

```js
// ember-cli-build.js
const EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  let app = new EmberApp(defaults, {
    (...)
    'esw-cache-fallback': {
      patterns: [
        '/', // <= This is the new line
        'http://json-api.rockandrollwithemberjs.com/(.+)',
        'https://rarwe-rails-api.herokuapp.com/(.+)'
      ], // These have to be regexes
      version: '1' // Changing the version will bust the cache
    }
    (...)
});
```

Is this what you recommend against? (That's also how it's done in [the www.201-shop.com](https://madhatted.com/2017/6/16/building-a-progressive-web-app-with-ember)).

**Comment by ghost** [comment]
Yes, I do not recommend caching FastBoot's `/` as a global index.html entry point.
If someone enters `/about` you will get a flash of `/` before the `/about`  page is rendered client side.
If you want to cache FastBoot responses, you will need to cache those individually and fall back to `index.html` when you don't have a FastBoot version cached. This addon does not support that yet.

Using `/` in cache fallback means you're not serving a cached version unless the network fails. It works, but isn't optimal.

**Comment by balinterdi** [comment]
So if I have a `patterns: ['/']` configured for ember-service-worker-cache-fallback, like above, then  I don't really need `ember-service-worker-index`, do I? (while understanding what you say above, that this is not optimal).

**Comment by ghost** [comment]
Yes, you could do without. But I would hate if that became a pattern that is thought to other people.

**Comment by balinterdi** [comment]
Understood.

> If you want to cache FastBoot responses, you will need to cache those individually and fall back to index.html when you don't have a FastBoot version cached. This addon does not support that yet.

That implies I'll have to consult you again for the book :) (I'd like to talk about PWAs at one point, sooner than later) as I'm unsure how that could be achieved.

Also, [Matt's PWA article](https://madhatted.com/2017/6/16/building-a-progressive-web-app-with-ember) follows the same, sub-optimal pattern.

**Comment by ghost** [comment]
Basically, you don't want that, what you want instead is to implement an [App Shell](https://developers.google.com/web/fundamentals/architecture/app-shell). 
I explain how this is done with Ember in my [EmberCamp 2017 talk](https://youtu.be/KgJ4mW3BtoA?t=8m34s).

I also just realized that the ESW-cache-fallback method is flawed, as in it only works for `/`. If a visitor enters your app through `/about` it won't match with the cached file. [ESW-index has logic](https://github.com/DockYard/ember-service-worker-index/blob/master/service-worker/index.js#L30-L43) to resolve any request of type `text/html`to `index.html`.

**Comment by balinterdi** [comment]
Sorry for coming back to this one, I watched the video and thought/tinkered about this some more but I'm still confused.

In your presentation, when talking about the App Shell model, you say right off the bat that if you use Fastboot you're done pretty quickly, so I guess we can make this work with Fastboot.

> If you want to cache FastBoot responses, you will need to cache those individually and fall back to index.html when you don't have a Fastboot version cached.

So if you want to cache the Fastboot response for `/about`, you include `\/about` as a regex in the config of ember-service-worker-cache-fallback. But how do you cache the Fastboot response for the root path? Isn't it by passing in `/` as a regex in cache-fallback? If so, we're back to square one, the non-recommended way.

> By default it (ember-service-worker-index) caches copy of /index.html, which FastBoot will serve as an asset.

I think that points to a misunderstanding I have about how service workers work in Fastboot/Node (if they work at all). Your statement seems to suggest that Fastboot can access the index.html version that was cached by the service worker (although, a version that was cached *before* had a chance to render content, so there are only placeholders). Is that so?

I appreciate your response and if there are any resources that shed light on my questions, just point me to those (the Google Developer article was useful, but not Ember-Fastboot specific). Thank you.

**Comment by ghost** [comment]
> So if you want to cache the Fastboot response for /about, you include \/about as a regex in the config of ember-service-worker-cache-fallback. But how do you cache the Fastboot response for the root path? Isn't it by passing in / as a regex in cache-fallback? If so, we're back to square one, the non-recommended way.

Yes, that's possible, but you can't just specify all your dynamic urls in there can you? So you need a better solution. One thing I'm thinking about is possible adding a FastBoot mode to this addon that lazily caches FastBoot's output and serves the regular index.html as a fallback. Allthough because it's a SPA, pages will only be cached when a user enters the app once, so it's actually kinda useless.

> I think that points to a misunderstanding I have about how service workers work in Fastboot/Node (if they work at all). Your statement seems to suggest that Fastboot can access the index.html version that was cached by the service worker (although, a version that was cached before had a chance to render content, so there are only placeholders). Is that so?

No, FastBoot also can double as a static file host for your assets. So ember-service-worker-index will cache `/index.html` served by the FastBoot server.

**Comment by balinterdi** [comment]
Thanks for the quick response.

So summing up, there is no quick-and-recommended way to create a perfect PWA with Fastboot. Do you have any working examples of what you'd consider an "idiomatic" PWA?

**Comment by ghost** [comment]
dockyard.com is a PWA running fastboot and a service worker.

**Comment by sandydoo** [comment]
So as I understand, DockYard is running a FastBoot server:
* as a static file host
* to serve pre-rendered HTML to new users *without* a registered service worker or cached js
* to serve pre-rendered HTML to users *without* a service-worker-compatible browser
* to serve pre-rendered HTML to users with javascript *disabled* (nice notice you got there)

What you get is basically the same as a cached Ember app that also boots offline and you'll only ever see FastBoot working when you first visit the app.

Maybe the whole confusion about the way this addon and FastBoot interact is because DockYard barely uses the main selling point of FastBoot, which is to serve pre-rendered HTML. You've prioritised the service worker over pre-rendered content. And without a proper app shell, you end up seeing a blank page while waiting for Ember to boot. At a cursory glance, I too first thought this addon would provide a cached fallback for `index.html`, rather than serving it all the time. Seems others thought so too (also, I guess we get some resolution regarding this issue): https://github.com/DavyJonesLocker/ember-cli-one-script/issues/1 . Your [blog post](https://dockyard.com/blog/2017/02/17/page-load-improvements-with-app-shell ) about render times also doesn't mention the effect this addon has on FastBoot (I'm assuming you used it to pass Lighthouse's offline test) and neither do the ember service worker docs.

Another thing to keep in mind is that if you're not going to go all the way down the app shell rabbit hole, you might be better off using FastBoot's pre-rendered content if you care about first paint times, especially on less performant devices. I get better first paints for DockYard when I disable the service worker and render FastBoot's content.

**Comment by ghost** [comment]
@sandydoo We're working on that ;) See https://github.com/DockYard/ember-app-shell
